poll_interval: 60

channels:
- name: Moona
  id: UCP0BspO_AMEe3aQqqpo89Dg
  filters:
  - '(?i)MoonUtau'
  - '(?i)Karaoke'
  - '(?i)Unarchived'
- name: Okayu
  id: UCvaTdHTWBGv3MKj3KVqJVCw
  filters:
  - '(?i)ASMR'

uploaders:
- type: local
  config:
    path: /tmp/hoshinova
    base_url: http://localhost:3000

notifiers:
- type: discord
  config:
    webhook_url: 'https://discord.com/api/webhooks/...'
